Completed update_zettel_json function, fixed delete function, and fixed other minor issues

diff --git a/zet b/zet
--- a/zet
+++ b/zet
@@ -12,11 +12,11 @@ ZET_EDITOR=$EDITOR
 PUBLIC=$ZETDIR
 PRIVATE=$ZETDIR_PRIVATE
 OPTION=$PUBLIC
-BASE_DIR=$ZET_SCRIPT_DIR
+BASE_DIR=$ZET
 TWEEPY_CONF="$BASE_DIR/util/tweepy.conf"
 GIT_HOST="$GITHUB_URL/$(basename $OPTION)"
 AWS_CREDS="$HOME/.aws/credentials"
-WEBSITE_LOCAL_DIR="$REPOS/eliotkhachi.dev/zettelkasten"
+WEBSITE_LOCAL_DIR="$REPOS/eliotkhachi.dev"
 WEBSITE_BUCKET_NAME=$WEBSITE_BUCKET_NAME
 WEBSITE_CLOUDFRONT_DISTRIBUTION_ID=$WEBSITE_CLOUDFRONT_DISTRIBUTION_ID
 
@@ -108,13 +108,6 @@ x_create() {
     test -n "$line"
     
     echo "Committing: $line"
-    # parse the tags of the zet we just made and try to add them to registry
-    readarray -t file_tags <<< "$(x_tags $datetime | tr -d '#' | tr ' ' '\n')"
-    for j in "${file_tags[@]}"; do
-        $(x_register $j)
-    done
-    sort -uo "$(x_dir)/REGISTRY.md"{,}
-    echo "Committing: $line"
     $(x_push $line)
 
     if [[ -f "$TWEEPY_CONF" ]]; then
@@ -123,27 +116,29 @@ x_create() {
         x_zettel_repository "$datetime"
     fi
     
-    x_create_html $readme
+    x_create_html "$readme"
+    x_update_zettels_json
+    # aws s3 cp "$WEBSITE_LOCAL_DIR/$datetime.html" "s3://$WEBSITE_BUCKET_NAME/"
 }
 
 x_delete() {
     local dir="$(x_dir)"
     # Loop through all arguments provided
-    for zettel in "$dir/$@"; do
-        # Delete if in github Zk
-        if [ -d "$zettel" ]; then
-	        rm -rf "$zettel"
+    for zettel in "$@"; do
+        # Delete directory if in publicZk
+        if [ -d "$dir/$zettel" ]; then
+	        rm -rf "$dir/$zettel"
             echo "$(basename $zettel) has been deleted from $OPTION."
         else
             echo "$(basename $zettel) does not exist in $OPTION."
             echo "Usage: $@ should be zettel ids."
         fi
-        # 
-        if [ -f "$WEBSITE_LOCAL_DIR/$(basename $zettel).html" ]; then
-            rm -rf "$WEBSITE_LOCAL_DIR/$(basename $zettel).html"
-            echo "$(basename $zettel).html has been deleted from $WEBSITE_LOCAL_DIR."
+        # Delete html if in eliotkhachi.dev/zettelkasten
+        if [ -f "$WEBSITE_LOCAL_DIR/zettelkasten/$(basename $zettel).html" ]; then
+            rm -rf "$WEBSITE_LOCAL_DIR/zettelkasten/$(basename $zettel).html"
+            echo "$(basename $zettel).html has been deleted from $WEBSITE_LOCAL_DIR/zettelkasten/."
         else
-            echo "$(basename $zettel).html does not exist in $WEBSITE_LOCAL_DIR."
+            echo "$(basename $zettel).html does not exist in $WEBSITE_LOCAL_DIR/zettelkasten."
             echo "Usage: $@ should be zettel ids."
         fi
     done
@@ -175,7 +170,13 @@ x_edit() {
             x_zettel_repository "$datetime"
         fi
 
-        x_create_html $readme
+        x_create_html "$readme"
+        x_update_zettels_json
+
+        # aws s3 cp "$WEBSITE_LOCAL_DIR/$datetime.html" "s3://$WEBSITE_BUCKET_NAME/"
+        # aws cloudfront create-invalidation "$WEBSITE_CLOUDFRONT_DISTRIBUTION_ID$
+    else
+        echo "Error: Could not find $1 in $OPTION"
     fi
 }
 
@@ -295,17 +296,6 @@ x_read() {
     fi
 }
 
-## adds tag to the registry if it is not already there
-x_register() {
-    local dir registry
-    dir="$(x_dir)"
-    registry="$dir/REGISTRY.md"
-    readarray -t all_tags <<< "$(x_topics | tr -d '1. #')"
-    if [[ ! " ${all_tags[*]} " =~ " $1 " ]]; then
-        echo "1. #$1" >> $registry
-    fi
-}
-
 ## Sync zettels
 x_s3_sync() {
     if [ "$OPTION" != "$PUBLIC" ]; then return; fi
@@ -327,13 +317,14 @@ x_tags(){
     tail -1 $readme
 }
 
-## returns all tags from REGISTRY.md
+## print the registry object from zettels.json
 x_topics() {
-    local dir registry
-    dir="$(x_dir)"
-    registry="$dir/REGISTRY.md"
-    sort -uo "$registry"{,}
-    cat $registry | sed 's/^1.//g' | nl
+    if ! command -v jq &>/dev/null; then
+        echo "Error: jq is not installed. Please run \`sudo apt install jq\` before running this command."
+        exit 1
+    fi
+
+    jq '.registry' $OPTION/zettels.json
 }
 
 ## updates zettel whitelist
@@ -439,10 +430,10 @@ x_create_html() {
     title=$(head -n 1 "$input_file" | sed -n 's/^# //p')
     
     # Declare the file location for the output HTML file 
-    output_file="$WEBSITE_LOCAL_DIR/$zettel_id.html"
+    output_file="$WEBSITE_LOCAL_DIR/zettelkasten/$zettel_id.html"
 
     # Convert Markdown to HTML using pandoc
-    pandoc -f gfm "$input_file" -o "$output_file" --template="$OPTION/custom_template.html" --metadata title="$title" 
+    pandoc -f gfm "$input_file" -o "$output_file" --template="$BASE_DIR/custom_template.html" --metadata title="$title" 
     
     # Check if the conversion was successful
     if [ $? -eq 0 ]; then
@@ -453,6 +444,72 @@ x_create_html() {
 
     # Fix zettel links in html files per $WEBSITE_LOCAL_DIR directory structure:
     sed -i 's#<a href="\.\./\([0-9]\{12\}\)">#<a href="\./\1.html">#g' $output_file
+}
+
+x_update_zettels_json() {
+    echo "Updating zettels.json..."
+    cd "$OPTION" || return
+
+    # remove current zettels.json
+    rm -f zettels.json
+
+    ## CREATE ZETTELS.JSON
+    # Initialize empty arrays
+    zettels=()
+    declare -A registry # associative array for registry (dictionary w/ unique key-value pairs)
+
+    # Loop through each zettel directory
+    for dir in *; do
+        if [ -d "$dir" ]; then
+            id="$dir" # Get the zettel ID
+            readme="$OPTION/$dir/README.md" # Get readme from the zettel directory
+
+            # Extract title
+            title=$(head -n 1 "$readme" | sed 's/# //g' | sed 's/\(.*\)/"\1"/g')
+
+            # Extract and format tags
+            tags=$(tail -n 1 "$readme" | sed 's/## Tags//g' | sed 's/#//g') 
+            IFS=' ' read -ra tag_array <<< "$tags"
+
+            zettel_tags=""
+            array_length=${#tag_array[@]}
+            index=0
+            for tag in "${tag_array[@]}"; do 
+                registry["\"$tag\""]=1 ## Add unique tags to the registry
+                ## Add tags to zettel_tags array
+                if [ "$index" -eq "$((array_length-1))" ]; then
+                    zettel_tags+="\"$tag\""
+                else
+                    zettel_tags+="\"$tag\","
+                fi 
+                ((index++))
+            done 
+
+
+            # Add zettel data to the array
+            zettel_data="{\"title\": $title, \"id\": $id, \"tags\": [$zettel_tags]}"
+            zettels+=("$zettel_data")
+        fi
+    done
+
+    # Extract unique tags from the associative array
+    unique_tags=("${!registry[@]}")
+    # echo ${unique_tags[*]}
+
+    # Sort and rewrite the registry
+    registry_sorted=($(for tag in "${unique_tags[@]}"; do echo "$tag"; done | sort))
+
+    # Join and rewrite the data array elements with commas
+    IFS=, zettels="${zettels[*]}"
+    IFS=, registry="${registry_sorted[*]}"
+
+    # Create the JSON output
+    json_output="{\"zettels\": [$zettels], \"registry\": [$registry]}"
+
+    # Write the JSON output to a file
+    echo "$json_output" > zettels.json
+    echo "$json_output" > "$WEBSITE_LOCAL_DIR/resources/zettel.json"
+    echo "JSON data saved to zettels.json"
 }
 
 # -----------------------------------------
@@ -487,7 +544,6 @@ if [[ -n "$1" ]]; then
 	pull                   :    pulls zettelkasten from remote repo
 	push <<message>>       :    commits zettelkasten to remote repo
 	read <<zet_id>>        :    prints the contents of a zettel
-	register <<zet_tag>>   :    adds a tag to the registry if it's not there 
 	show <<zet_tag>        :    shows all zettels that have a matching tag
 	tags <<zet_id>>        :    returns all tags associated with zettel
 	topics                 :    returns all tags in the registry
