Added helper script to replace expressions in all zettels

diff --git a/zet b/zet
--- a/zet
+++ b/zet
@@ -9,13 +9,17 @@
 # -------------------------------------------------
 
 ZET_EDITOR=$EDITOR
+ZET_VIEWER=$VIEWER
 PUBLIC=$ZETDIR
 PRIVATE=$ZETDIR_PRIVATE
 OPTION=$PUBLIC
-BASE_DIR=$ZET_SCRIPT_DIR
+BASE_DIR=$ZET
 TWEEPY_CONF="$BASE_DIR/util/tweepy.conf"
 GIT_HOST="$GITHUB_URL/$(basename $OPTION)"
 AWS_CREDS="$HOME/.aws/credentials"
+WEBSITE_LOCAL_DIR="$REPOS/eliotkhachi.dev"
+WEBSITE_BUCKET_NAME=$WEBSITE_BUCKET_NAME
+WEBSITE_CLOUDFRONT_DISTRIBUTION_ID=$WEBSITE_CLOUDFRONT_DISTRIBUTION_ID
 
 r='\e[31m' # red
 g='\e[32m' # green
@@ -36,7 +40,7 @@ z='\e[30m' # black
 ## returns all zettels from the session directory
 x_all() {
     local dir="$(x_dir)"
-    ls $dir | grep -Ev '.md|.json'
+    ls $dir | grep -Ev '.md$|.json$|.css$|.html$|.sh$'
 }
 
 ## configures twitter api for python
@@ -88,6 +92,7 @@ x_create() {
     if [[ "$#" -lt 1 ]]; then
         exit 1;
     fi
+    # create zettel directory, readme, and title the readme 
     local title="$*"
     local dir readme datetime
     datetime="$(x_isomin)"
@@ -95,17 +100,14 @@ x_create() {
     readme="$dir/README.md"
     mkdir -p "$dir"
     printf "%s\n\n%s\n" "# $title" "## Tags" > "$readme"
+    
+    ## open editor
     "$ZET_EDITOR" "$readme"
     cd "$dir" &>/dev/null
     [[ -s "$dir/README.md" ]] || return 1
     line=$(head -1 "$dir/README.md" | sed 's/^# //')
     test -n "$line"
-    # parse the tags of the zet we just made and try to add them to registry
-    readarray -t file_tags <<< "$(x_tags $datetime | tr -d '#' | tr ' ' '\n')"
-    for j in "${file_tags[@]}"; do
-        $(x_register $j)
-    done
-    sort -uo "$(x_dir)/REGISTRY.md"{,}
+    
     echo "Committing: $line"
     $(x_push $line)
 
@@ -114,15 +116,49 @@ x_create() {
         x_zettel_mapping
         x_zettel_repository "$datetime"
     fi
+
+    if [[ "$OPTION" == "$PUBLIC" ]]; then
+        x_create_html "$readme"
+    fi
+    x_update_zettels_json
 }
 
-## sets the session directory to either the public or private zk
+x_delete() {
+    local dir="$(x_dir)"
+    # Loop through all arguments provided
+    for zettel in "$@"; do
+        # Delete directory if in publicZk
+        if [ -d "$dir/$zettel" ]; then
+	        rm -rf "$dir/$zettel"
+            echo "$(basename $zettel) has been deleted from $OPTION."
+        else
+            echo "$(basename $zettel) does not exist in $OPTION."
+            echo "Usage: $@ should be zettel ids."
+        fi
+        # Delete html if in eliotkhachi.dev/zettelkasten
+        if [ -f "$WEBSITE_LOCAL_DIR/zettelkasten/$(basename $zettel).html" ]; then
+            rm -rf "$WEBSITE_LOCAL_DIR/zettelkasten/$(basename $zettel).html"
+            echo "$(basename $zettel).html has been deleted from $WEBSITE_LOCAL_DIR/zettelkasten/."
+        else
+            echo "$(basename $zettel).html does not exist in $WEBSITE_LOCAL_DIR/zettelkasten."
+            echo "Usage: $@ should be zettel ids."
+        fi
+
+        if [[ "$OPTION" == "$PUBLIC" ]]; then
+            aws s3 rm "s3://$WEBSITE_BUCKET_NAME/zettelkasten/$(basename $zettel).html"
+            aws cloudfront create-invalidation --distribution-id $WEBSITE_CLOUDFRONT_DISTRIBUTION_ID --paths="/zettelkasten/$(basename $zettel).html" &> /dev/null
+        fi 
+    done
+    x_update_zettels_json
+}
+
+##  sets the session directory to OPTION
 x_dir() {
-    local dir="$OPTION"
-    mkdir -p "$dir" && echo "$dir"
+	local dir="$OPTION"
+	mkdir -p "$dir" && echo "$dir"
 }
 
-## edits a zettel and pushes it to respective remote repo
+## edits a zettel and pushes it to public repo
 x_edit() {
     readarray -t directories <<< "$(x_all)"
     if [[ " ${directories[*]} " =~ " $1 " ]]; then
@@ -141,6 +177,13 @@ x_edit() {
             x_zettel_mapping
             x_zettel_repository "$datetime"
         fi
+
+        if [[ "$OPTION" == "$PUBLIC" ]]; then
+            x_create_html "$readme"
+        fi
+        x_update_zettels_json
+    else
+        echo "Error: Could not find $1 in $OPTION"
     fi
 }
 
@@ -160,12 +203,14 @@ x_show() {
     fi
     readarray -t directories <<< "$(x_all)"
     for i in "${directories[@]}"; do
-        readarray -t tags <<< "$(tail -1 $dir/$i/README.md | tr ' ' '\n')"
-        for j in "${tags[@]}"; do
-            if [[ $j == $tag ]]; then
-                echo -ne "$a$i$x - $y$(head -1 "$dir/$i/README.md" | sed 's/^# //')$x\n" 
-            fi
-        done
+        if [[ -d "$dir/$i" ]]; then
+            readarray -t tags <<< "$(tail -1 $dir/$i/README.md | tr ' ' '\n')"
+            for j in "${tags[@]}"; do
+                if [[ $j == $tag ]]; then
+                    echo -ne "$a$i$x - $y$(head -1 "$dir/$i/README.md" | sed 's/^# //')$x\n" 
+                fi
+            done
+        fi
     done 
 }
 
@@ -177,35 +222,36 @@ x_isomin() { date -u +%Y%m%d%H%M ; }
 x_link() {
     readarray -t directories <<< "$(x_all)"
     if [[ " ${directories[*]} " =~ " $1 " ]]; then
-        link="[$(head -1 "$(x_dir)/$1/README.md" | sed 's/^# //')]($GIT_HOST/tree/main/$1)"
+        # link="[$(head -1 "$(x_dir)/$1/README.md" | sed 's/^# //')]($GIT_HOST/tree/main/$1)"
+        link="[$(head -1 "$(x_dir)/$1/README.md" | sed 's/^# //')](../$1)"
         echo "$link"
     fi
 }
 
 x_snip() {
-    local s3_images_region="us-west-1"
-    local s3_images_bucket="zettelimages"
-    # set temporary image location
-    image_loc="/tmp/$(date | sed 's/ /_/g').png"
+    # init image location
+    image_loc="$WEBSITE_LOCAL_DIR/resources/zettel-images/$(date | sed 's/ /_/g').png"
+
     if [[ "$1" == "pc" ]]; then
         # screenshot desktop area and save image
-        gnome-screenshot -ap -f $image_loc # prompts user to select an area
+        gnome-screenshot -ap -f $image_loc
     elif [[ "$1" == "rm" ]]; then
         # screenshot reMarkable tablet and save image
-        reSnap -s $REMARKABLE_IP -n -o $image_loc > /dev/null 2> /dev/null
-     elif [[ "$1" == "select" ]]; then
-         # pick an image or gif from your computer
-         cp $(zenity --file-selection --file-filter='Image files | *.png *.jpg *.gif') $image_loc
+        reSnap -s $REMARKABLE_IP -n -o $image_loc &> /dev/null
+    elif [[ "$1" == "select" ]]; then
+        # pick an image or gif from your computer
+        cp "$(zenity --file-selection --file-filter='Image files | *.png *.jpg *.gif')" $image_loc
     elif [[ "$1" == "ipad" ]]; then
-        echo "Not yet implemented..."
+        echo Not yet implemented...
     else
         echo "invalid usage: -h or --help for help"
         exit 0
     fi
     # upload image to s3
-    aws s3api put-object --bucket $s3_images_bucket --key $(basename $image_loc) --body $image_loc --content-type="image/png" > /dev/null
+    x_upload "resources/zettel-images/$(basename $image_loc)"
+
     # echo link to the s3 object
-    echo "![image](https://s3.$s3_images_region.amazonaws.com/$s3_images_bucket/$(basename $image_loc))"
+    echo "![image](https://www.eliotkhachi.dev/resources/zettel-images/$(basename $image_loc))"
 }
 
 ## post a zettelkasten link to twitter
@@ -236,36 +282,29 @@ x_pull() {
 
 ## pushes zettelkasten changes to respective remote repo
 x_push() {
-    local dir="$(x_dir)"
-    cd "$dir" &>/dev/null
-    git add -A "$dir" &>/dev/null
-    if [[ -n "$*" ]]; then
-        git commit -m "$*" &>/dev/null
-    else
-        git commit -m "Updated Zettelkasten: $(date -u)" &>/dev/null
+    if [[ "$OPTION" == "$PUBLIC" ]]; then
+        local dir="$(x_dir)"
+        cd "$dir" &>/dev/null
+        git add -A "$dir" &>/dev/null
+        if [[ -n "$*" ]]; then
+            git commit -m "$*" &>/dev/null
+        else
+            git commit -m "Updated Zettelkasten: $(date -u)" &>/dev/null
+        fi
+        git push
     fi
-    git push
 }
 
 ## reads the contents of a given zettel
 x_read() {
-    readarray -t directories <<< "$(x_all)"
-    if [[ " ${directories[*]} " =~ " $1 " ]]; then
-        # $ZET_EDITOR -R "$(x_dir)/$1/README.md"
-	xdg-open $GIT_HOST/tree/main/$1 2> /dev/null
-        # Another option; pros: safer, cons: annoying (q! instead of q to quit)
-        # $ZET_EDITOR - < "$(x_dir/$1/README.md)"
-    fi
-}
-
-## adds tag to the registry if it is not already there
-x_register() {
-    local dir registry
-    dir="$(x_dir)"
-    registry="$dir/REGISTRY.md"
-    readarray -t all_tags <<< "$(x_topics | tr -d '1. #')"
-    if [[ ! " ${all_tags[*]} " =~ " $1 " ]]; then
-        echo "1. #$1" >> $registry
+    if [[ "$OPTION" == "$PUBLIC" ]]; then
+        readarray -t directories <<< "$(x_all)"
+        if [[ " ${directories[*]} " =~ " $1 " ]]; then
+	    	xdg-open $GIT_HOST/tree/main/$1 2> /dev/null
+            # firefox $OPTION/$1/README.md
+        fi
+    else
+        view $OPTION/$1/README.md
     fi
 }
 
@@ -290,13 +329,14 @@ x_tags(){
     tail -1 $readme
 }
 
-## returns all tags from REGISTRY.md
+## print the registry object from zettels.json
 x_topics() {
-    local dir registry
-    dir="$(x_dir)"
-    registry="$dir/REGISTRY.md"
-    sort -uo "$registry"{,}
-    cat $registry | sed 's/^1.//g' | nl
+    if ! command -v jq &>/dev/null; then
+        echo "Error: jq is not installed. Please run \`sudo apt install jq\` before running this command."
+        exit 1
+    fi
+
+    jq '.registry' $OPTION/zettels.json
 }
 
 ## updates zettel whitelist
@@ -317,7 +357,7 @@ x_zk() {
         year="${i:0:4}"
         month="${i:4:2}"
         day="${i:6:2}"
-        echo -ne "$a$month/$day/$year$x - $y$msg$x ($p$i$x)\n"
+        echo -ne "$a$month/$day/$year$x - $y$msg$x ($p$i$x) $g$tags$x\n"
     done | less -r 
 }
 
@@ -349,6 +389,167 @@ x_zettel_repository() {
         aws s3 cp "$OPTION/$1/README.md" "$s3_bucket/$1.md" &> /dev/null
     fi
 }
+## recommit all zettels (makes a slight change to each zettel by adding a space at the end of the title)
+## PROGRESS
+    # Commit message are fixed to reflect zettel titles 
+    # Commit dates still aren't fixed
+x_fix_commits() { 
+    local dir="$(x_dir)"
+    cd $dir
+    # if [[ "$dir" == "$PUBLIC" ]]; then
+        # loop through each directory in your zettelkasten
+        for i in $(ls $dir | grep -v '.md'); do
+            # parse dir name to store the commit date and time in the format: "2020.11.02 12:00"
+            date=$(date -d "${i:0:8} ${i:8:2}:${i:10:2}" +"\"%Y.%m.%d %H:%M\"")
+
+            # parse 1st line of zettel (the title) to get commit message
+            readme="$dir/$i/README.md" # get zettel readme
+            msg=$(cat "$readme" | head -n 1 | sed 's/^#\s//') # get 1st line, contents after "#"
+            sed -i '1s/$/ /' $readme  ## make a slight change to the zettel (add a space at end of title)
+            # echo $msg $date
+            git commit -a --message="$msg" --date="$date"
+        done
+    # else 
+    #     echo "Recommit aborted. This is a private repository."
+    # fi
+}
+
+x_create_html() {
+    # Check if pandoc is installed
+    if ! command -v pandoc &>/dev/null; then
+      echo "Error: pandoc is not installed. Please install pandoc before running this script."
+      exit 1
+    fi
+
+    # Check if the correct number of arguments is provided
+    if [ "$#" -ne 1 ]; then
+      echo "Usage: $0 input.md"
+      exit 1
+    fi
+    
+    # Declare variables
+    local dir="$(x_dir)"
+    input_file="$1"
+    zettel_id=$(basename $(dirname $input_file))
+    
+    # Check if the input file exists
+    if [ ! -f "$input_file" ]; then
+      echo "Error in x_create_html: The input file '$input_file' does not exist."
+      exit 1
+    fi
+
+    # Get title from zettel
+    title=$(head -n 1 "$input_file" | sed -n 's/^# //p')
+    
+    # Declare the file location for the output HTML file 
+    output_file="$WEBSITE_LOCAL_DIR/zettelkasten/$zettel_id.html"
+
+
+    # Convert Markdown to HTML using pandoc
+    pandoc -f gfm -t html -F mermaid-filter "$input_file" -o "$output_file" --template="$BASE_DIR/custom_template.html" --metadata title="$title" 
+    # pandoc "$input_file" -o "$output_file" --css=https://raw.githubusercontent.com/sindresorhus/github-markdown-css/main/github-markdown.css --template="$BASE_DIR/custom_template.html" --metadata title="$title" 
+    
+    # Check if the conversion was successful
+    if [ $? -eq 0 ]; then
+      echo "Conversion successful. HTML file saved as $output_file"
+    else
+      echo "Error: HTML Conversion failed."
+    fi
+
+    # Fix zettel links in html files per $WEBSITE_LOCAL_DIR directory structure:
+    sed -i 's#<a href="\.\./\([0-9]\{12\}\)">#<a href="\./\1.html">#g' $output_file
+
+    x_upload "zettelkasten/$zettel_id.html"
+}
+
+x_upload() {
+    if [[ "$OPTION" == "$PUBLIC" ]]; then
+        if [ "$#" -ne 1 ]; then
+            echo "Usage: $0 single_input_file"
+            exit 1
+        fi
+
+        file=$1
+    
+        # Check if the file exists
+        if [ ! -f "$WEBSITE_LOCAL_DIR/$file" ]; then
+          echo "Error uploading. The file '$file' does not exist."
+          exit 1
+        fi
+        
+        echo "Uploading $WEBSITE_LOCAL_DIR/$file..."
+        aws s3 cp --quiet $WEBSITE_LOCAL_DIR/$file s3://$WEBSITE_BUCKET_NAME/$file
+        aws cloudfront create-invalidation --distribution-id $WEBSITE_CLOUDFRONT_DISTRIBUTION_ID --paths="/$file" &> /dev/null
+    fi
+}
+    
+x_update_zettels_json() {
+    echo "Updating zettels.json..."
+    cd "$OPTION" || return
+    
+    # remove current zettels.json
+    rm -f zettels.json
+
+    ## CREATE ZETTELS.JSON
+    # Initialize empty arrays
+    zettels=()
+    declare -A registry # associative array for registry (dictionary w/ unique key-value pairs)
+
+    # Loop through each zettel directory
+    for dir in *; do
+        if [ -d "$dir" ]; then
+            id="$dir" # Get the zettel ID
+            readme="$OPTION/$dir/README.md" # Get readme from the zettel directory
+
+            # Extract title
+            title=$(head -n 1 "$readme" | sed 's/# //g' | sed 's/\(.*\)/"\1"/g')
+
+            # Extract and format tags
+            tags=$(tail -n 1 "$readme" | sed 's/## Tags//g' | sed 's/#//g') 
+            IFS=' ' read -ra tag_array <<< "$tags"
+
+            zettel_tags=""
+            array_length=${#tag_array[@]}
+            index=0
+            for tag in "${tag_array[@]}"; do 
+                registry["\"$tag\""]=1 ## Add unique tags to the registry
+                ## Add tags to zettel_tags array
+                if [ "$index" -eq "$((array_length-1))" ]; then
+                    zettel_tags+="\"$tag\""
+                else
+                    zettel_tags+="\"$tag\","
+                fi 
+                ((index++))
+            done 
+
+
+            # Add zettel data to the array
+            zettel_data="{\"title\": $title, \"id\": $id, \"tags\": [$zettel_tags]}"
+            zettels+=("$zettel_data")
+        fi
+    done
+
+    # Extract unique tags from the associative array
+    unique_tags=("${!registry[@]}")
+    # echo ${unique_tags[*]}
+
+    # Sort and rewrite the registry
+    registry_sorted=($(for tag in "${unique_tags[@]}"; do echo "$tag"; done | sort))
+
+    # Join and rewrite the data array elements with commas
+    IFS=, zettels="${zettels[*]}"
+    IFS=, registry="${registry_sorted[*]}"
+
+    # Create the JSON output
+    json_output="{\"zettels\": [$zettels], \"registry\": [$registry]}"
+
+    # Write the JSON output to a file
+    echo "$json_output" > zettels.json
+    echo "$json_output" > "$WEBSITE_LOCAL_DIR/resources/zettels.json"
+
+    x_upload "resources/zettels.json"
+}
+
 
 # -----------------------------------------
 # ---- handling command line args ---------
@@ -371,24 +572,22 @@ if [[ -n "$1" ]]; then
         ------------------------------------------------------------------------
         commands:
         ------------------------------------------------------------------------
-        all                    :    lists all zettels
-        create <<zet>>         :    creates a new zettel
-        dir                    :    gets session directory 
-        edit <<zet_id>>        :    make changes to a zettel & push it
-        isomin                 :    returns the datetime as YYYYMMDDHHMM (UTC)
-        link <<zet_id>>        :    echoes the markdown to link to a zettel
-        post <<zet_id>>>       :    tweets zettelkasten title, tags, link
-        pull                   :    pulls zettelkasten from remote repo
-        push <<message>>       :    commits zettelkasten to remote repo
-        read <<zet_id>>        :    prints the contents of a zettel
-        register <<zet_tag>>   :    adds a tag to the registry if it's not there 
-        s3_sync                :    syncs all the local zettels to the s3 repo
-        show <<zet_tag>        :    shows all zettels that have a matching tag
-        tags <<zet_id>>        :    returns all tags associated with zettel
-        topics                 :    returns all tags in the registry
-        whitelist              :    changes the whitelisted zettels on DynamoDB
-        zk                     :    show all zettels in friendly format
-
+	all                    :    lists all zettels
+	create <<zet>>         :    creates a new zettel
+	delete <<zet_id>>      :    deletes a zettel
+	dir                    :    gets session directory 
+	edit <<zet_id>>        :    make changes to a zettel & push it
+	isomin                 :    returns the datetime as YYYYMMDDHHMM (UTC)
+	link <<zet_id>>        :    echoes the markdown to link to a zettel
+	post <<zet_id>>>       :    tweets zettelkasten title, tags, link
+	pull                   :    pulls zettelkasten from remote repo
+	push <<message>>       :    commits zettelkasten to remote repo
+	read <<zet_id>>        :    prints the contents of a zettel
+	show <<zet_tag>        :    shows all zettels that have a matching tag
+	tags <<zet_id>>        :    returns all tags associated with zettel
+	topics                 :    returns all tags in the registry
+	zk                     :    show all zettels in friendly format
+        snip <<device>>        :    takes a screenshot - device=pc,rm,select
         ------------------------------------------------------------------------
         options:
         ------------------------------------------------------------------------
@@ -401,7 +600,7 @@ if [[ -n "$1" ]]; then
     ## sets the session directory to $PRIVATE else it defaults to $PUBLIC
     if [[ "$1" == "--private" || "$1" == "-p" ]]; then
         OPTION=$PRIVATE
-	GIT_HOST="$GITHUB_URL/$(basename $PRIVATE)"
+		GIT_HOST="$GITHUB_URL/$(basename $PRIVATE)"
         shift 1
     fi
 
